#!/bin/bash
#
# Tool to synchronize versioned and system dot files.
#
# Depends on:
# - rsync

SYNC="rsync -av --progress --delete"

# Array of 'system | versioned' file couples
common=(
    # bash
    "$HOME/.bashrc | bash/bashrc"
    "$HOME/.bash_profile | bash/bash_profile"
    "$HOME/.profile | bash/profile"
    "$HOME/.inputrc | bash/inputrc"
    # gnupg
    "$HOME/.gnupg/gpg-agent.conf | gnupg/gpg-agent.conf"
    # fonts configuration
    "$HOME/.config/fontconfig/ | fontconfig/"
    # git
    "$HOME/.config/git/ | git/"
    # helix
    "$HOME/.config/helix/ | helix/"
    # zellij
    "$HOME/.config/zellij/ | zellij/"
    # cosmic
    "$HOME/.config/cosmic/ | cosmic"
    # fuzzel (used by rofimoji)
    "$HOME/.config/fuzzel/ | fuzzel/"
    # rofimoji
    "$HOME/.config/rofimoji.rc | rofimoji/rofimoji.rc"
    # alacritty
    "$HOME/.config/alacritty/ | alacritty/"
    # broot
    "$HOME/.config/broot/ | broot/"
    # ranger
    "$HOME/.config/ranger/ | ranger/"
    # yazi
    "$HOME/.config/yazi/ | yazi/"
    # gitui
    "$HOME/.config/gitui/ | gitui/"
    # zathura
    "$HOME/.config/zathura/ | zathura/"
    # tridactyl
    "$HOME/.config/tridactyl/ | tridactyl/"
    # lldb
    "$HOME/.lldbinit | lldb/lldbinit"
    "$HOME/.lldb/scripts/ | lldb/scripts/"
    # Mime associations
    "$HOME/.config/mimeapps.list | misc/mimeapps.list"
    # ssh
    "$HOME/.ssh/config | ssh/config"
    # OTP tool
    "$HOME/.config/otp/ | otp/"
    # Systemd
    "$HOME/.config/systemd/user/inputd.service | systemd/user/inputd.service"
)

behemoth=(
    # wayvnc
    "$HOME/.config/wayvnc/ | wayvnc/"
    # samba
    "/etc/samba/smb.conf | samba/smb.conf"
    # evremap
    "/etc/evremap.toml | evremap/evremap.toml"
)

workmule_files=(
    # evremap
    "/etc/evremap.toml | evremap/evremap.toml"
)

if [[ $1 == "out" ]]; then
    echo "Syncing OUT"
    out=1
elif [[ $1 == "in" ]]; then
    echo "Syncing IN"
    out=0
else
    echo "Usage: sync in|out [--confirm]"
    echo "  in : copy files from system folders"
    echo "  out: copy files to system folders"
    echo "  --confirm: prompt for confirmation before synchronization"
    exit
fi

confirm=0
if [[ $2 == "--confirm" ]]; then
    confirm=1
fi

function sync_files() {
    target="$1"
    echo "[$target]"

    shift
    files=("$@")

    for file in "${files[@]}"; do
        system_file=$(echo $file | cut -d'|' -f1 | sed 's/^ *//;s/ *$//')
        local_file=$(echo $file | cut -d'|' -f2 | sed 's/^ *//;s/ *$//')
        local_file="$target/$local_file"

        if [[ $out == 1 ]]; then
            in_file=$local_file
            out_file=$system_file
        else
            in_file=$system_file
            out_file=$local_file
        fi

        echo "* " $in_file ">" $out_file

        if [[ $confirm == 1 ]]; then
            printf "proceed [N/y]? "
            read confirmed
        else
            confirmed="y"
        fi

        if [[ $confirmed == "y" ]]; then
            if [[ -f "$in_file" ]] || [[ -d "$in_file" ]]; then
                mkdir -p $(dirname "$out_file")
                $SYNC $in_file $out_file
            else
                echo "Skipping unexistent file \"$in_file\""
            fi
        fi
    done
}

# Sync common files
sync_files "common" "${common[@]}"

# Sync system specific files
sync_files "$HOSTNAME" "${behemoth[@]}"
