[[language]]
name = "rust"
formatter = { command = "rustfmt", args = [ "+nightly" ] }

[language.debugger]
command = "lldb"
name = "lldb"
transport = "stdio"

# Language Server configuration
[[language.config]]
extraEnv = { CHALK_OVERFLOW_DEPTH = 3000, CHALK_SOLVER_MAX_SIZE = 1500 }

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true
