[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["+nightly"] }

[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
file-types = ["md", "txt", "adoc"]
scope = "source.markdown"
roots = []

# Language Server configuration
[[language.config]]
extraEnv = { CHALK_OVERFLOW_DEPTH = 3000, CHALK_SOLVER_MAX_SIZE = 1500 }

# [language.debugger]
# command = "codelldb"
# name = "codelldb"
# port-arg = "--port {}"
# transport = "tcp"

[language.debugger]
command = "lldb-vscode-14"
name = "lldb-vscode-14"
transport = "stdio"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" }]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "binary (terminal)"
request = "launch"
completion = [ { name = "binary", completion = "filename" }]
args = { program = "{0}", runInTerminal = true }
