# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[manager]
append_keymap = [
  { on = [ "g", "e" ], run = "arrow 99999999", desc = "Move cursor to the bottom" }
]
