#!/usr/bin/env bash

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
export HISTCONTROL=ignoreboth:erasedups
# For setting history length see HISTSIZE
export HISTSIZE=2000
# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

# Disable START/STOP output control.
# Do not interpret Ctrl-s and Ctrl-q as flow signals for terminal output.
# Zellij disables it anyway (but we may exit zellij)
stty -ixon

# Disable shell exit when reading EOF 
set -o ignoreeof

# Enable vi mode
set -o vi
