inherits = "gruvbox"

"ui.virtual.inlay-hint" = { fg = "gray1", modifiers = ["italic"] }

[palette]

bg0 = "#282828" # main background
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"
# bg_s = "#101010" # cursor line background

fg0 = "#fbf1c7"
fg1 = "#d4be98"
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984"

gray = "#a89984"
gray0 = "#a89984"
gray1 = "#7a6f60"

red0 = "#ea6962"
red1 = "#ea6962"
green0 = "#a9b665"
green1 = "#a9b665"
yellow0 = "#e78a4e"
yellow1 = "#e3a84e"
blue0 = "#7daea3"
blue1 = "#7daea3"
purple0 = "#b16286"
purple1 = "#d3869b"
aqua0 = "#689d6a"
aqua1 = "#8ec07c"
orange0 = "#d65d0e"
orange1 = "#fe8019"
