#!/usr/bin/env bash

# VPN config files
export VPN_CONFIG_DIR="$HOME/.wireguard"

# Default options for 'fzf'
export FZF_DEFAULT_OPTS="--history=/tmp/fzf-history --no-sort --exact"

# Default editor
export EDITOR="$HOME/bin/hx"

# Default terminal
export TERMINAL=alacritty

# Enable Wayland for Firefox
export MOZ_ENABLE_WAYLAND=1

# Exclude the specified folders from the zoxide database
#export _ZO_EXCLUDE_DIRS="/mnt/data/*"

# Resolve symlinks before adding directories to the database
export _ZO_RESOLVE_SYMLINKS=1

# WOB socket
export WOB_SOCK="/run/user/$(id -u)/wob.sock"

# Dark theme for gtk applications
export GTK_THEME="Adwaita:dark"

# Folders for go stuff 
export GOPATH="$HOME/.go"

# To make wayland clipboard work
export COSMIC_DATA_CONTROL_ENABLED="1"

# Local folder for pip venvs
export PIP_LOCAL_VENVS="$HOME/.local/pip"

# File where we write the last visited folder
export CWD_FILE="/tmp/${USER}_cwd_file"

# By default libvirt uses 'qemu:///session'
export LIBVIRT_DEFAULT_URI="qemu:///system"
