#!/usr/bin/env bash

# Add user's private binaries
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Add binaries installed via 'cargo' to PATH
if [ -d "$HOME/.cargo/bin" ] ; then
    PATH="$HOME/.cargo/bin:$PATH"
fi

# Add binaries installed via 'go' to PATH
if [ -d "$HOME/.go/bin" ] ; then
    PATH="$HOME/.go/bin:$PATH"
fi

# Add more binaries
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
