# ltex-ls config: https://valentjn.github.io/ltex/settings.html
[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]
file-types = ["md", "txt", "adoc"]
scope = "source.markdown"

[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["+nightly"] }

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["--indent", "4"] }

[language-server.rust-analyzer]
# NOTE: Looks like `ra-multiplex` ignores the variables
# command = "ra-multiplex"
environment = { "SKIP_WASM_BUILD" = "1", "CARGO_TARGET_DIR" = "target/rust-analyzer" }
# args = ["--verbose"]

# [language.debugger]
# command = "codelldb"
# name = "codelldb"
# port-arg = "--port {}"
# transport = "tcp"

[language.debugger]
command = "lldb-vscode"
name = "lldb-vscode"
port-arg = "--port {}"
transport = "tcp"

# [language.debugger]
# command = "lldb"
# transport = "stdio"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" }]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "binary (terminal)"
request = "launch"
completion = [ { name = "binary", completion = "filename" }]
args = { program = "{0}", runInTerminal = true }

[[language]]
name = "asn1"
scope = "source.asn1"
file-types = ["asn", "asn1"]
roots = []
comment-tokens = "--"
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "asn1"
source = { git = "https://github.com/JonathanWilbur/tree-sitter-asn1", rev = "c5b9d6427490fbbfd96d7717301866623e9114c0" }
