# ltex-ls config: https://valentjn.github.io/ltex/settings.html
[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]
file-types = ["md", "txt", "adoc"]
scope = "source.markdown"

[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["+nightly"] }

[language-server.rust-analyzer]
# NOTE: Looks like `ra-multiplex` ignores the variables
# command = "ra-multiplex"
environment = { "SKIP_WASM_BUILD" = "1", "CARGO_TARGET_DIR" = "target/rust-analyzer" }
# args = ["--verbose"]

# [language.debugger]
# command = "codelldb"
# name = "codelldb"
# port-arg = "--port {}"
# transport = "tcp"

[language.debugger]
command = "lldb-vscode"
name = "lldb-vscode"
port-arg = "--port {}"
transport = "tcp"

# [language.debugger]
# command = "lldb"
# transport = "stdio"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" }]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "binary (terminal)"
request = "launch"
completion = [ { name = "binary", completion = "filename" }]
args = { program = "{0}", runInTerminal = true }
