# ~/.bash_profile
#
# Version 0.1.0

# Add user's private binaries
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Add binaries installed via 'cargo' to PATH
if [ -d "$HOME/.cargo/bin" ] ; then
    PATH="$HOME/.cargo/bin:$PATH"
fi

# Add more binaries
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Default folder for go stuff 
GOPATH="$HOME/.go"
GOROOT="$HOME/.go"

# Default options for 'fzf'
export FZF_DEFAULT_OPTS="--history=/tmp/fzf-history --no-sort --exact"

# Default editor
export EDITOR="$HOME/bin/hx"

# Enable Wayland for Firefox
export MOZ_ENABLE_WAYLAND=1

# Exclude the specified folders from the zoxide database
#export _ZO_EXCLUDE_DIRS="/mnt/data/*"

# Resolve symlinks before adding directories to the database
export _ZO_RESOLVE_SYMLINKS=1

# WOB socket
export WOB_SOCK="/run/user/$(id -u)/wob.sock"

# Dark theme for gtk applications
export GTK_THEME="Adwaita:dark"

# Include .bashrc if it exists
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi
