# ~/.bash_profile

# Remember fzf search history
export FZF_DEFAULT_OPTS="--history=/tmp/fzf-history --no-sort --exact"

# Fix for lldb-14
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016436
# Probably solved in lldb-15?
export PYTHONPATH="/usr/lib/llvm-14/lib/python3.11/dist-packages"

# Default editor
export EDITOR="/home/davxy/bin/hx"

# Enable Wayland for Firefox
export MOZ_ENABLE_WAYLAND=1

# Exclude the specified folders from the zoxide database
#export _ZO_EXCLUDE_DIRS="/mnt/data/*"

# Resolve symlinks before adding directories to the database
export _ZO_RESOLVE_SYMLINKS=1

# WOB socket
export WOB_SOCK="/run/user/$(id -u)/wob.sock"

# Dark theme for gtk applications
export GTK_THEME="Adwaita:dark"

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# include .bashrc if it exists
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi
