#!/bin/bash

OPEN_OVERVIEW='{"Action":{"OpenOverview":{}}}'
CLOSE_OVERVIEW='{"Action":{"CloseOverview":{}}}'

if pgrep -x "fuzzel" > /dev/null; then
    pkill -x "fuzzel"
    echo "$CLOSE_OVERVIEW" | socat - UNIX-CONNECT:"$NIRI_SOCKET"
    exit 0
fi

commands="poweroff reboot lock suspend bluetooth wifi"

echo "$OPEN_OVERVIEW" | socat - UNIX-CONNECT:"$NIRI_SOCKET" > /dev/null
chosen=$(printf '%s\n' $commands | fuzzel --dmenu)
echo "$CLOSE_OVERVIEW" | socat - UNIX-CONNECT:"$NIRI_SOCKET" > /dev/null

[ -z "$chosen" ] && exit 0

case "$chosen" in
    bluetooth)
        alacritty -e bluetui &
        ;;
    wifi)
        alacritty -e impala &
        ;;
    lock)
        swaylock
        ;;
    poweroff|reboot|suspend)
        systemctl "$chosen"
        ;;
esac
