#!/bin/bash

OPEN_OVERVIEW='{"Action":{"OpenOverview":{}}}'
CLOSE_OVERVIEW='{"Action":{"CloseOverview":{}}}'

if pgrep -x "fuzzel" > /dev/null; then
    pkill -x "fuzzel"
    echo "$CLOSE_OVERVIEW" | socat - UNIX-CONNECT:"$NIRI_SOCKET"
    exit 0
fi

commands="poweroff reboot suspend bluetui impala"

echo "$OPEN_OVERVIEW" | socat - UNIX-CONNECT:"$NIRI_SOCKET" > /dev/null
chosen=$(printf '%s\n' $commands | fuzzel --dmenu)
echo "$CLOSE_OVERVIEW" | socat - UNIX-CONNECT:"$NIRI_SOCKET" > /dev/null

[ -z "$chosen" ] && exit 0

case "$chosen" in
    bluetui|impala)
        alacritty -e "$chosen" &
        ;;
    poweroff|reboot|suspend)
        systemctl "$chosen"
        ;;
esac
